### PR TITLE
[Sprint 5 & 6] form creation, add/remove buttons, better CSS and navigation

### PR DESCRIPTION
**Pull request by stevahnes**

### CODE REVIEW

**Comment by stevahnes** [comment]
[Create from Scratch](https://trello.com/c/baJjc3u8/3-create-from-scratch)

**Comment by stevahnes** [comment]
I will try to add test cases tomorrow :) But you can take a look at the code if you want!

**Comment by zeyao** [comment]
LGTM!

**Comment by zeyao** [comment]
Just a reminder when doing merge please do squash and merge

**Review by zeyao — APPROVED** [review]

**Comment by stevahnes** [comment]
I'll squash the last 4 commits then! The others have some PR merge stuff

**Pull request merged**
